"""Build reports/error_examples.md from reports/error_analysis.csv (real failed test examples + computed patterns)."""
from __future__ import annotations

import collections
import csv
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src.config import MODEL_DISPLAY, REPORTS, SEED  # noqa: E402

N_EXAMPLES = 24


def cell(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ")


def main() -> None:
    rows = list(csv.DictReader(open(REPORTS / "error_analysis.csv", encoding="utf-8")))
    out = ["# Error analysis (held-out test split)", "",
           "Generated by `scripts/summarize_errors.py` from `reports/error_analysis.csv`. Examples are sampled with a fixed seed "
           f"({SEED}) from real failures; the pattern tables are counts computed from the same file. No text here is written by a model.", ""]
    for key in dict.fromkeys(r["model"] for r in rows):
        mr = [r for r in rows if r["model"] == key]
        out += [f"## {MODEL_DISPLAY.get(key, key)}: {len(mr)} failed test rows", ""]
        ic = [r for r in mr if "intent" in r["error_types"].split("|")]
        pairs = collections.Counter((r["true_intent"], r["pred_intent"]) for r in ic)
        out += ["### Most confused intent pairs", "", "| True | Predicted | Count |", "|---|---|---:|"]
        out += [f"| `{t}` | `{p}` | {n} |" for (t, p), n in pairs.most_common(8)] + [""]
        by_lang = collections.Counter(r["language"] for r in ic)
        out += ["### Intent errors by language (count only; see evaluation for rates)", "", "| Language | Intent errors | Median tokens of failed msgs |", "|---|---:|---:|"]
        for l, n in sorted(by_lang.items()):
            toks = sorted(int(r["n_tokens"]) for r in ic if r["language"] == l)
            out.append(f"| {l} | {n} | {toks[len(toks) // 2]} |")
        out.append("")
        ue = [r for r in mr if r["true_urgency"] and r["true_urgency"] != r["pred_urgency"]]
        levels = ["very_low", "low", "medium", "high", "critical"]
        over = sum(levels.index(r["pred_urgency"]) > levels.index(r["true_urgency"]) for r in ue)
        miss = [r for r in mr if "missed_escalation" in r["error_types"]]
        fals = [r for r in mr if "false_escalation" in r["error_types"]]
        out += ["### Urgency / escalation failures", "",
                f"- urgency wrong: {len(ue)} texts ({over} over-predicted, {len(ue) - over} under-predicted)",
                f"- missed escalations (true=yes, predicted no): {len(miss)}; false escalations (true=no, predicted yes): {len(fals)}",
                f"- by language: " + ", ".join(f"{l}: {n}" for l, n in sorted(collections.Counter(r['language'] for r in ue + miss + fals).items())), ""]
        rnd = random.Random(SEED)
        sample = rnd.sample(mr, min(N_EXAMPLES, len(mr)))
        # make sure synthetic (urgency/escalation) failures are represented
        syn = [r for r in mr if r["true_urgency"] or r["true_escalation"]]
        for r in rnd.sample(syn, min(6, len(syn))):
            if r not in sample:
                sample[rnd.randrange(len(sample))] = r
        out += [f"### {len(sample)} sampled failures", "",
                "| Input | Lang | True intent | Pred. intent | True urgency | Pred. urgency | True esc. | Pred. esc. (p) |", "|---|---|---|---|---|---|---|---|"]
        for r in sample:
            esc_t = {"1": "yes", "0": "no", "": "–"}[r["true_escalation"]]
            esc_p = ({"1": "yes", "0": "no"}[r["pred_escalation"]] + f" ({float(r['escalation_probability']):.2f})") if r["pred_escalation"] != "" else "–"
            out.append(f"| {cell(r['text'])} | {r['language']} | {r['true_intent'] or '–'} | {r['pred_intent'] or '–'} | {r['true_urgency'] or '–'} | {r['pred_urgency'] or '–'} | {esc_t} | {esc_p} |")
        out.append("")
    (REPORTS / "error_examples.md").write_text("\n".join(out), encoding="utf-8")
    print("wrote reports/error_examples.md")


if __name__ == "__main__":
    main()
